version: "2"
services:
  server:
    container_name: server
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - server/.env
    links:
      - mongo
  gurobi:
    container_name: gurobi
    build:
      context: gurobi
      dockerfile: Dockerfile
    ports:
      - 1234:1234
  client:
    container_name: client
    build:
      context: client
      dockerfile: Dockerfile
    ports:
      - 8000:80
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
