version: "3.4"
services:
  server:
    container_name: server
    build:
      network: host
      context: server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - server/.env
    links:
      - mongo
  client:
    container_name: client
    build:
      network: host
      context: client
      dockerfile: Dockerfile
    ports:
      - "8000:80"
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
